### ISSUE TITLE
PayPal Express refuses transaction when there is an offer on the order.

### ISSUE THREAD

**Issue by maxgarfinkel** [BroadleafCommerce/blc-paypal#12]
Module: Broadleaf-paypal:2.6.0-GA
Broadleaf Version 3.1.3-GA

The paypal express module cannot successfully complete a transaction when there is an offer on the order (It works fine when the offer is on an order item). The error message from pay pal is: The totals of the cart item amounts do not match order amounts.

Steps to reproduce:
1. Create an offer for a discount on an order.
2. Add a qualifying item to your cart
3. Add the offer code
4. complete checkout on heat clinic
5. Paypal payment is refused.

Full error message
[TRACE] 16:44:34 PayPalExpressHostedServiceImpl - Request to PayPal Express Checkout Hosted Endpoint with raw response: TIMESTAMP=2014-12-03T16:44:34Z&CORRELATIONID=a51dd80fe54d7&ACK=Failure&VERSION=78.0&BUILD=14086142&L_ERRORCODE0=10413&L_SHORTMESSAGE0=Transaction refused because of an invalid argument. See additional error messages for details.&L_LONGMESSAGE0=The totals of the cart item amounts do not match order amounts.&L_SEVERITYCODE0=Error

**Comment by elbertbautista** [comment]
@maxgarfinkel: Have you extended our default implementation to pass in line item information so that PayPal displays it on their side? To our knowledge, this error only  happens if you've extended our `OrderToPaymentRequestDTOService` to pass in line item information. If you have done this, then that means you also need to take into account any offers or adjustments at that level as well. The PayPal API has their own restriction and checks to make sure the total of the items match the total of the order - their API doesn't allow for passing in Order level adjustments. To account for this, one way is to create another negative line item in your implementation, so that the totals are accounted for. Please reference the README for the PayPal module that talks about this:

https://github.com/BroadleafCommerce/blc-paypal
See the section entitled: `Showing Line Items on PayPal Express's Checkout Screen` and scroll to the bottom to see how to account for order level adjustments and possibly fulfillment fees if necessary.
